---
title: "Maps"
format: html
---

```{r}
library(sf)
library(mapview)
```

## Maps

### Main locations

First, we plot the five locations in the `cherry.csv` file

```{r}
#| label: map-main-locations
#| eval: false

cherry_coord <- cherry |> 
  group_by(location) |> 
  slice_tail(n = 1)

cherry_map <- cherry_coord |> 
  st_as_sf(coords = c("long", "lat"), crs = 4326)

mapview(cherry_map, zcol = "alt")
```

### Japan

Next, we plot the map of all the locations in the `japan.csv` file

```{r}
#| label: map-japan
#| eval: false

crd_ch <- japan |> 
  filter(!is.na(bloom_doy)) |> 
  group_by(location, long, lat, alt) |> 
  summarise(n = n())

map_ch <- crd_ch |> 
  st_as_sf(coords = c("long", "lat"), crs = 4326)

mapview(map_ch, zcol = "n")
```

### Korea

Second, we plot the locations in the `south_korea.csv` file

```{r}
#| label: map-korea
#| eval: false

crd_korea <- korea |> 
  filter(!is.na(bloom_doy)) |> 
  group_by(location, long, lat, alt) |> 
  summarise(n = n())

map_korea <- crd_korea |> 
  st_as_sf(coords = c("long", "lat"), crs = 4326)

mapview(map_korea, zcol = "n")
```

### Switzerland

Third, we plot the locations in the `meteoswiss.csv` file

```{r}
#| label: map-meteoswiss
#| eval: false

crd_ch <- meteoswiss |> 
  filter(!is.na(bloom_doy)) |> 
  group_by(location, long, lat, alt) |> 
  summarise(n = n())

map_ch <- crd_ch |> 
  st_as_sf(coords = c("long", "lat"), crs = 4326)

mapview(map_ch, zcol = "n")
```
